ad=input("Adiniz nedir?\n")
yas=input("Nece yasiniz var?\n")
pese=input("Peseniz nedir?\n")
hobby=input("Hobbiniz nedir?\n")
boy=float(input("Boyunuz nece metrdir?\n"))
ceki=int(input("Nece kilogramsiz?\n"))
bmi = boy / (ceki * ceki)
print(ad , yas , pese , hobby, boy , ceki , bmi)
print("Salam, sizin adınız", ad, "dir və", yas, "yaşınız var. Sizin peşəniz", pese, "dir və ən sevdiyiniz hobbi", hobby, "dır. \nBədən indeksiniz:", bmi)
